name: todoAPI testing

on:
  push:
    branches: [ master, develop ]

jobs:

  build:
    name: Unit-Testing
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install Hugo
      run: go test -v ./...

    - name: Send message to Telegram
      uses: Lukasss93/telegram-action@v1
      env:
        TELEGRAM_TOKEN: ${{ secrets.telegram_token }}
        TELEGRAM_CHAT: ${{ secrets.telegram_chat }}
